### PR TITLE
Add pre-commit tool

### PR DESCRIPTION
**Pull request by KAUTH**
In this PR, we add the pre-commit tool to
improve the Software Development Lifecycle
of the project by automatically running checks
(mainly linting & formatting) before one commits their changes.

- Specifically:
* flake8, isort and black were adjusted in tox to run as a pre-commit hooks
* Additionally, added hooks were:
 - the check-added-large-files - prevents giant files from being committed
 - end-of-file-fixer - ensures that a file is either empty or ends with one newline
 - trailing-whitespace - trims trailing whitespace
 - check-yaml - checks yaml files for parseable syntax
* we added a local hook with pre-commit that calls tox to check if `make requirements` is up-to-date

- The Pipfile dev-packages were updated to include pre-commit.

- We updated the README.md with how to install and enable pre-commit.

- We ran `make requirements`.

- Fix tox requirements check failing

### CODE REVIEW

**Comment by MVrachev** [comment]
@KAUTH could you apply the changes we discussed in pr https://github.com/vmware/repository-service-tuf-cli/pull/110 here as well?

**Comment by KAUTH** [comment]
> @KAUTH could you apply the changes we discussed in pr https://github.com/vmware/repository-service-tuf-cli/pull/110 here as well?

Yes, now that the mentioned PR is merged I will apply the changes here too.

**Review by MVrachev — APPROVED** [review]
I had a look at the changes and they seem the same as in the https://github.com/vmware/repository-service-tuf-cli/pull/110 pr.

@KAUTH could you also add issues like https://github.com/vmware/repository-service-tuf-cli/issues/124 and https://github.com/vmware/repository-service-tuf-cli/issues/125 for this repo as well?
I will appreciate it if you do the same for the RSTUF API.

I ask you this as the above issues are only related to the CLI and we want to make sure we track those things in the RSTUF API and worker as well.

**Comment by KAUTH** [comment]
> I had a look at the changes and they seem the same as in the [vmware/repository-service-tuf-cli#110](https://github.com/vmware/repository-service-tuf-cli/pull/110) pr.
> 
> @KAUTH could you also add issues like [vmware/repository-service-tuf-cli#124](https://github.com/vmware/repository-service-tuf-cli/issues/124) and [vmware/repository-service-tuf-cli#125](https://github.com/vmware/repository-service-tuf-cli/issues/125) for this repo as well? I will appreciate it if you do the same for the RSTUF API.
> 
> I ask you this as the above issues are only related to the CLI and we want to make sure we track those things in the RSTUF API and worker as well.

Hey @MVrachev, thanks for the review. I am creating the issues as well 👍🏻

**Review by MVrachev — APPROVED** [review]
Awesome, thanks @KAUTH!

**Pull request merged**
